# Server port to listen on
port: 8080

# JWT signing key used for issuing and verifying tokens
jwt_secret: "super-secret-key"

# Enable debug logging
debug: true

# Authentication provider to use: currently only "local" is supported
auth_provider: local

# === Database Configuration ===

# Select database driver (options: sqlite, mysql, postgres, sqlserver, clickhouse)
database: "sqlite"

# Connection string / DSN (Data Source Name) for the database
database_dsn: "/home/javad/goIAM/iam.db"  # For SQLite, this is a file path

# --- Examples for other databases (commented out) ---

# PostgreSQL example:
# database: "postgres"
# database_dsn: "host=localhost user=postgres password=secret dbname=iamdb port=5432 sslmode=disable"

# MySQL example:
# database: "mysql"
# database_dsn: "user:password@tcp(localhost:3306)/iamdb?charset=utf8mb4&parseTime=True&loc=Local"

# SQL Server example:
# database: "sqlserver"
# database_dsn: "sqlserver://user:password@localhost:1433?database=iamdb"

# ClickHouse example:
# database: "clickhouse"
# database_dsn: "tcp://localhost:9000?username=default&password=&database=iamdb"
