# Application name used in CLI output and logs
# Can be overridden with environment variable IAM_APP_NAME
appName: "goIAM"

# Server name shown in HTTP headers or UI
# Can be overridden with environment variable IAM_SERVER_NAME
serverName: "goIAM Server"

# Server port to listen on
port: 8080

# JWT signing key used for issuing and verifying tokens
jwt_secret: "super-secret-key"

# Enable debug logging
debug: true

# Authentication provider to use: currently only "local" is supported
auth_provider: local

# === Database Configuration ===

# Select database driver (options: sqlite, mysql, postgres, sqlserver, clickhouse)
database: "sqlite"

# Connection string / DSN (Data Source Name) for the database
database_dsn: "./iam.db"  # For SQLite, this is a file path

# --- Examples for other databases (commented out) ---

# PostgreSQL example:
# database: "postgres"
# database_dsn: "host=localhost user=postgres password=secret dbname=iamdb port=5432 sslmode=disable"

# MySQL example:
# database: "mysql"
# database_dsn: "user:password@tcp(localhost:3306)/iamdb?charset=utf8mb4&parseTime=True&loc=Local"

# SQL Server example:
# database: "sqlserver"
# database_dsn: "sqlserver://user:password@localhost:1433?database=iamdb"

# ClickHouse example:
# database: "clickhouse"
# database_dsn: "tcp://localhost:9000?username=default&password=&database=iamdb"

# === Validation Configuration ===

# Configure validation rules using regex patterns or numeric limits.
# These are optional and have reasonable defaults if omitted.

# validation:
#   email_regex: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"            # Simple RFC-like email format
#   phone_regex: "^\\+?[0-9]{7,15}$"                         # E.164 format or local digits
#   password_regex: "^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d@$!%*#?&]{6,}$"  # Letters + numbers
#   website_regex: "^https?://[\\w\\-\\.]+\\.\\w+"           # Basic http/https URL
#   password_min_length: 6                                   # Minimum password length
